# DEFINIR UMA VARIAVEL
x = 10

# DEFINIR MULTIPLAS VARIÁVEIS COM VALORES DISTINTOS
x, y, z = 10, 20, 30

# DEFINIR MULTIPLAS VARIÁVEIS COM O MESMO VALOR
x = y = z = 10

# O PYTHON TEM TIPAGEM DINÂMMICA, OU SEJA, PODE MUDAR SEU TIPO DURANTE O CÓDIGO
X = 10 # AQUI É UM INTERGER
print(type(X))

X = "MUDOU" # AGORA, AQUI É UM STRING
print(type(X))